version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        image: nginx:latest
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./source:/var/www/html/localhost
        tty: true
        stdin_open: true
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80