version: "3.8"
services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    tty: true
    stdin_open: true
    env_file:
      - ./.env