version: '3'
services:
    nginx-1:
        build:
            context: .
            dockerfile: Dockerfile
        image: nginx-1:latest
        container_name: nginx-1
        ports:
            - 8080:80
        volumes:
            - ./source:/var/www/html/localhost
        tty: true
        stdin_open: true
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
    nginx-2:
        image: nginx:latest
        container_name: nginx-2
        ports:
            - 8090:80
        tty: true
        stdin_open: true
